export const SET_UPCOMING = 'SET_UPCOMING'
export const ADD_ALBUMS = 'ADD_ALBUMS'
export const SET_POPULAR = 'SET_POPULAR'
export const ADD_ARTISTS = 'ADD_ARTISTS'
export const SET_TOPRATED = 'SET_TOPRATED'
export const ADD_PLAYLIST = 'ADD_PLAYLIST'
